### PR TITLE
Removed generic scripts without functional tie to AppMetrics.

### PR DESCRIPTION
**Pull request by sopel**
This pull request supersedes and thus closes #105.

@mrdavidlaing - Given the release of the [AWS Tools for Windows PowerShell](http://aws.amazon.com/powershell/) I think we should base our Windows specific scripting solely on this approach, which renders those scripts originally queued for migration to https://github.com/cityindex/labs-operations obsolete in their current form at least.

I've started documentation on how to achieve the same goal via PowerShell in [
Scripting instance operations via PowerShell](https://github.com/cityindex/labs-operations/wiki/Scripting-instance-operations-via-PowerShell) - the documented  'one liners' could still be converted into respective scripts again to improve usability, i.e. ease usage by calling a dedicated script for specific every day operations like a red button stop of a particular instance set.

If you agree, this pull request could be merged (and #105 closed accordingly - lacking write access my respective inline command has correctly been ignored).

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
Agreed as to approach and deletion.

Note that the stop functionality in these scripts has been superseded by a
stop button build into Appmetrics itself, so these scripts are no longer
needed anyway.

On Monday, January 28, 2013, Steffen Opel wrote:

> This pull request supersedes and thus closes #105https://github.com/fandrei/AppMetrics/issues/105
> .
> 
> @mrdavidlaing https://github.com/mrdavidlaing - Given the release of
> the AWS Tools for Windows PowerShell http://aws.amazon.com/powershell/I think we should base our Windows specific scripting solely on this
> approach, which renders those scripts originally queued for migration to
> https://github.com/cityindex/labs-operations obsolete in their current
> form at least.
> 
> I've started documentation on how to achieve the same goal via PowerShell
> in
> Scripting instance operations via PowerShellhttps://github.com/cityindex/labs-operations/wiki/Scripting-instance-operations-via-PowerShell\- the documented 'one liners' could still be converted into respective
> scripts again to improve usability, i.e. ease usage by calling a dedicated
> script for specific every day operations like a red button stop of a
> particular instance set.
> 
> ## If you agree, this pull request could be merged.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/sopel/AppMetrics remove-generic-scripts
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/fandrei/AppMetrics/pull/131
> Commit Summary
> - Removed generic scripts without functional tie to AppMetrics.
> 
> File Changes
> - _D_ Scripts/AWSSDK.dll (0)
> - _D_ Scripts/start_all_tagged_nodes.ps1 (48)
> - _D_ Scripts/stop_all_tagged_nodes.ps1 (49)
> - _D_ Scripts/stop_start_tagged_nodes.md (43)
> 
> Patch Links:
> - https://github.com/fandrei/AppMetrics/pull/131.patch
> - https://github.com/fandrei/AppMetrics/pull/131.diff

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
I guess we should remove this branch as well?
https://github.com/fandrei/AppMetrics/tree/stop-start-collectors-script

**Comment by sopel** [comment]
@fandrei - absolutely, the GitHub suggestion and shortcut for deleting the branches backing already merged pull requests is usually a good indicator; in fact I can picture only a few rare cases where this isn't desired (e.g. merging several times from a long running branch, which is best avoided in the first place for simple DVCS workflows like ours) ...

**Comment by sopel** [comment]
... even though that pull request obviously hasn't actually been merged, I spoke too quickly ;) - I'd still say it doesn't provide anything which must be retained, but that's for the owner of the pull request @mrdavidlaing to decide then.

**Comment by mrdavidlaing** [comment]
Delete the puppy guys.

On Monday, January 28, 2013, Steffen Opel wrote:

> ... even though that pull request obviously hasn't actually been merged, I
> spoke too quickly ;) - I'd still say it doesn't provide anything which must
> be retained, but that's for the owner of the pull request @mrdavidlainghttps://github.com/mrdavidlaingto decide then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fandrei/AppMetrics/pull/131#issuecomment-12793023.

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Pull request merged**
